* Git utilities by Hraban Luyat

Lisp utilities. Currently just the one: =git-graft=.

* Commands

Follow the installation steps and add the binary to your path. You can invoke commands as sub commands of the binary, e.g.:

#+begin_src shell
hly-git-tools git-graft foo bar
#+end_src

Or you can (sym)link the binary to its command name, add /that/ to your PATH, and invoke it directly:

#+begin_src shell
(
  cd "$(dirname "$(which hly-git-tools)")"
  ln -s hly-git-tools git-graft
)

git graft foo bar
#+end_src

This uses the git convention that any executable called =git-something= on your path will be picked up by the top-level =git= tool and exposed as =git something=.

** =git-graft=

#+begin_src shell :eval never-export
git
#+end_src

* Installation
** Native

You probably want this:

1. Install [[https://www.sbcl.org/][SBCL]]:
   =$ brew install sbcl=
2. Install [[https://www.quicklisp.org/][Quicklisp]] (follow the full instructions, up to and including =(ql:add-to-init-file)=)
3. From this directory:
   =$ mkdir -p ~/quicklisp/local-projects && ln -fs "$PWD/src/" ~/quicklisp/local-projects/hly-git-utils=
4. =$ ./ql-install-deps.lisp=
5. =$ ./build.lisp=

You now have a binary =hly-git-utils= in the =./dist/= directory which you can
move wherever you want and run, even without Lisp installed.

To recompile the source later, you only need to run the last step.

I’ve tested this on Mac, it should work on Linux, and maybe even on Windows? Let
me know if it works for you.

** Docker

If you insist on Docker:

#+begin_src shell
docker build -t hly-git-utils .
#+end_src

Pros: easy peasy.

Cons: you have to run it dockerized. That’s slow and annoying, especially on Mac
and Windows.

* License

hly-git-tools - Git utilities
Copyright © 2022  Hraban Luyat

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, version 3 of the License.


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

