name: "Test"

on:
  push:
  pull_request:

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: linux
            id: ubuntu-latest
          - name: macos
            id: macos-latest
    runs-on: ${{ matrix.os.id }}
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
          trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v4
    - name: Channel-based Nix
      run: nix-build
    - name: "Flake: regular build"
      run: "nix build --print-build-logs"
      # This will need to recompile SBCL
    - name: "Flake: build with purged Nix references"
      run: "nix build --print-build-logs .#norefs"
    - name: "Upload stand-alone binary"
      uses: actions/upload-artifact@v4
      with:
        name: git-hly-${{ matrix.os.name }}-${{ github.sha }}
        path: result/bin/git-hly
