name: "Test"

on:
  push:
  pull_request:

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
          trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: actions/checkout@v4
    - name: Channel-based Nix
      run: nix-build
    - name: Flake
      run: nix build
