name: "Test"

on:
  push:
  pull_request:

jobs:
  nix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
          trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - name: Channel-based Nix
      run: nix-build
    - name: Flake
      run: nix build
